numpy:
  # python 3.7-3.9
  - 1.16    # [not (osx and arm64)]
  - 1.16    # [not (osx and arm64)]
  - 1.16    # [not (osx and arm64)]
  # python 3.8-3.9
  - 1.19    # [osx and arm64]
  - 1.19    # [osx and arm64]
  # python 3.10
  - 1.21
  # python 3.11
  - 1.23
python:
  - 3.11
