{% set name = "setuptools" %}
{% set version = "67.8.0" %}
{% set build = "0" %}
{% set checksum = "62642358adc77ffa87233bc4d2354c4b2682d214048f500964dbe760ccedf102" %}

# make sure to set CONDA_ADD_PIP_AS_PYTHON_DEPENDENCY=0 environ-variable before building it
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools/setuptools-{{ version }}.tar.gz
  sha256: {{ checksum }}
  patches:
    # Modify setuptools to fail if used in conda build (encourage people to add all deps in meta.yaml).
    - patches/0002-disable-downloads-inside-conda-build.patch
    # distutils patches from python-feedstock
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch

build:
  number: 0
  skip: True               # [py<37]
  entry_points:
    # distutils.commands
    - alias=setuptools.command.alias:alias
    - bdist_egg=setuptools.command.bdist_egg:bdist_egg
    - bdist_rpm=setuptools.command.bdist_rpm:bdist_rpm
    - build=setuptools.command.build:build
    - build_clib=setuptools.command.build_clib:build_clib
    - build_ext=setuptools.command.build_ext:build_ext
    - build_py=setuptools.command.build_py:build_py
    - develop=setuptools.command.develop:develop
    - dist_info=setuptools.command.dist_info:dist_info
    - easy_install=setuptools.command.easy_install:easy_install
    - editable_wheel=setuptools.command.editable_wheel:editable_wheel
    - egg_info=setuptools.command.egg_info:egg_info
    - install=setuptools.command.install:install
    - install_egg_info=setuptools.command.install_egg_info:install_egg_info
    - install_lib=setuptools.command.install_lib:install_lib
    - install_scripts=setuptools.command.install_scripts:install_scripts
    - rotate=setuptools.command.rotate:rotate
    - saveopts=setuptools.command.saveopts:saveopts
    - sdist=setuptools.command.sdist:sdist
    - setopt=setuptools.command.setopt:setopt
    - test=setuptools.command.test:test
    - upload_docs=setuptools.command.upload_docs:upload_docs
    # setuptools.finalize_distribution_options
    - parent_finalize=setuptools.dist:_Distribution.finalize_options
    - keywords=setuptools.dist:Distribution._finalize_setup_keywords
    # distutils.setup_keywords
    - eager_resources=setuptools.dist:assert_string_list
    - namespace_packages=setuptools.dist:check_nsp
    - extras_require=setuptools.dist:check_extras
    - install_requires=setuptools.dist:check_requirements
    - tests_require=setuptools.dist:check_requirements
    - setup_requires=setuptools.dist:check_requirements
    - python_requires=setuptools.dist:check_specifier
    - entry_points=setuptools.dist:check_entry_points
    - test_suite=setuptools.dist:check_test_suite
    - zip_safe=setuptools.dist:assert_bool
    - package_data=setuptools.dist:check_package_data
    - exclude_package_data=setuptools.dist:check_package_data
    - include_package_data=setuptools.dist:assert_bool
    - packages=setuptools.dist:check_packages
    - dependency_links=setuptools.dist:assert_string_list
    - test_loader=setuptools.dist:check_importable
    - test_runner=setuptools.dist:check_importable
    - use_2to3=setuptools.dist:invalid_unless_false
    # egg_info.writers
    - PKG-INFO=setuptools.command.egg_info:write_pkg_info
    - requires.txt=setuptools.command.egg_info:write_requirements
    - entry_points.txt=setuptools.command.egg_info:write_entries
    - eager_resources.txt=setuptools.command.egg_info:overwrite_arg
    - namespace_packages.txt=setuptools.command.egg_info:overwrite_arg
    - top_level.txt=setuptools.command.egg_info:write_toplevel_names
    - depends.txt=setuptools.command.egg_info:warn_depends_obsolete
    - dependency_links.txt=setuptools.command.egg_info:overwrite_arg

requirements:
  build:
    - patch                # [unix]
    - m2-patch             # [win]
  host:
    # omitting wheel for this package to avoid cyclic dependencies
    - python
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - setuptools
    - pkg_resources
    - distutils

about:
  home: https://github.com/pypa/setuptools
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  doc_url: https://setuptools.pypa.io/en/latest/
  dev_url: https://github.com/pypa/setuptools

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - nicoddemus
    - isuruf
