{% set version = "36.2.2" %}

package:
  name: setuptools
  version: {{ version }}

source:
  fn: setuptools-{{ version }}.tar.gz
  url: https://github.com/pypa/setuptools/archive/v{{ version }}.tar.gz
  sha256: d49f3a855f8b370633cd1ad7f36d8f247e536fff229e319d7d3d8913bce7afdf
  patches:
    # Modify setuptools to fail if used in conda build (encourage people to add all deps in meta.yaml).
    - nodownload.patch

build:
  number: 0
  entry_points:
    - easy_install = setuptools.command.easy_install:main

requirements:
  host:
    - python
    - certifi
    - wincertstore  # [win]
  run:
    - python
    - certifi
    - wincertstore  # [win]

test:
  commands:
    - easy_install --help
  imports:
    - setuptools
    - easy_install
    - pkg_resources

about:
  home: https://github.com/pypa/setuptools
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  doc_url: http://pythonhosted.org/setuptools/
  dev_url: https://github.com/pypa/setuptools

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - nicoddemus
    - mingwandroid
