{% set name = "setuptools" %}
{% set version = "80.7.1" %}
{% set checksum = "f6ffc5f0142b1bd8d0ca94ee91b30c0ca862ffd50826da1ea85258a06fd94552" %}

# make sure to set CONDA_ADD_PIP_AS_PYTHON_DEPENDENCY=0 environ-variable before building it locally
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/setuptools/setuptools-{{ version }}.tar.gz
  sha256: {{ checksum }}
  patches:
    - patches/0002-disable-downloads-inside-conda-build.patch
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch

build:
  number: 0
  skip: true  # [py<39]
  missing_dso_whitelist:  # [win]
    - $RPATH/MSVCR71.dll  # [win]
    - $RPATH/MSVCR80.dll  # [win]

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    # omitting wheel for this package to avoid cyclic dependencies
    - python
    - coherent.licensed
    - pip
  run:
    - python
    - pytest >=6.2.0
    - termcolor >=2.1.0
    - packaging >=21.3
  run_constrained:
    - pytest >=6,!=8.1.*
    - pytest-checkdocs >=2.4
    - packaging >=24.2
    - more_itertools >=8.8
    - jaraco.text >=3.7
    - wheel >=0.44.0
    - platformdirs >=4.2.2
    - jaraco.functools >=4
    - sphinx >=3.5
    - jaraco.packaging >=9.3
    - rst.linker >=1.9
    - jaraco.tidelift >=1.4
    - pygments-github-lexers ==0.0.5
    - sphinx-notfound-page >=1,<2
    - pyproject-hooks !=1.1
    - towncrier <24.7
    - pytest-enabler >=2.2
    - virtualenv >=13.0.0
    - pip >=19.1
    - jaraco.envs >=2.2
    - pytest-xdist >=3
    - jaraco.path >=3.7.2
    - python-build >=1.0.3
    - filelock >=3.4.0
    - ini2toml >=0.14
    - tomli-w >=1.0.0
    - pytest-home >=0.5
    - jaraco.test >=5.5
    - mypy ==1.14.*

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - setuptools
    - pkg_resources

about:
  home: https://github.com/pypa/setuptools
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  doc_url: https://setuptools.pypa.io
  dev_url: https://github.com/pypa/setuptools

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - nicoddemus
    - isuruf
  skip-lints:
    # As we are bootstrapping this build we do not require python build tools
    - missing_python_build_tool
    - missing_wheel