{% set name = "setuptools" %}
{% set version = "60.9.3" %}
{% set build = "0" %}
{% set checksum = "2347b2b432c891a863acadca2da9ac101eae6169b1d3dfee2ec605ecd50dbfe5" %}

# make sure to set CONDA_ADD_PIP_AS_PYTHON_DEPENDENCY=0 environ-variable before building it
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools/setuptools-{{ version }}.tar.gz
  sha256: {{ checksum }}
  patches:
    # Modify setuptools to fail if used in conda build (encourage people to add all deps in meta.yaml).
    - patches/0002-disable-downloads-inside-conda-build.patch
    # distutils patches from python-feedstock
    - patches/0012-Disable-new-dtags-in-unixccompiler.py.patch  # [py<=39]
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
    - patches/0010-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch  # [py<=39 and python_impl=="cpython"]

build:
  number: 0
  skip: True               # [py<37]

requirements:
  build:
    - patch                # [unix]
    - m2-patch             # [win]
  host:
    # omitting wheel for this package to avoid cyclic dependencies
    - python
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - setuptools
    - pkg_resources

about:
  home: https://github.com/pypa/setuptools
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  doc_url: https://setuptools.pypa.io/en/latest/
  dev_url: https://github.com/pypa/setuptools

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - nicoddemus
    - isuruf
  skip-lints:
    # skip linter's checks for wheel and python build tool: not there to avoid cyclic dependencies
    - missing_wheel
    - missing_python_build_tool

