travis:
  secure:
    BINSTAR_TOKEN: inVbcGUOJ51gIj4TpSOEQVV9bMn1HQpYgZUEFGy7k46bfl8r1khLswCGtoBSVVrHqenupPynpUN1nYeWgzDG8puy9ba1GWM3DuVuQCMe5YeDDrGPBGEwWRiAM+TvoFTrmkb593T1W7mZAPtTNxEVDhGaidAiub+EioJM5k0lQG26ScjHDAaLn2X8Fu8VWLdCAyBn+mvUhZJ2RReDJ3oTIHME/Q4Nlmtd1x6RHRGIvbphBdwS6zDCmR9NFWD57LcumpETmbof1eoakRYR7JteIuxWb/PHIt5F4QtMzr1pNMOCeLNqmc0c/9+IfUdZtgzsRS8iEg3f0yCH2EAycr0uI+WDFPvC8SSausuau6f98uOqW8JQsyjVR5kaGgk620006wbmgsd3gVvLU/GYXQGcKTngf6gU3FwvBP72b3NTlPGTu5wdsLX7b46FZFxIjdnjkZteOp5S6bQ0MGNXxZxvVIQr6v5/3LwgcvnI52vXMUvw8wP66ZeGUTeUxk/RHMQfq8n6IFvBzlui4efxQa3StASAp+3Zi7OYZfAEN1uH8hvGqBdO3lkuIycoY0tMf7KxMJRI/wXv8zoq999DnC8Y4DEp9HYgewEUx+pYs1SxkKrIaYR2OOhlDpBp3+jLMI5clOGC/9478dAjy9tMYyQtqAIWl/Hne8PJP/ctnh7HmY4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
