travis:
  secure:
    BINSTAR_TOKEN: BcKJtzpX4mQFddgHFJB9uxShmlBr/WHeUKSonB9tRno2n6jt7L3jDPhUi42C1XBlyMNj7tuUwqgNuF1X6HNQe4L0xC0o1X6IvexG/bRJaLF6zfEAS9iM7j7v+FA71ynrTWk+6k1dkIN0Ck3CRA2cpT2DKz0vOSG88D8T6iOcJkT+qC3GcfL3QqvJHOoq+ygkXqf/LRi6ee+o9AWwbrNhQWq8Ex64rT6t9bTDJ9JoL45U/FSr4yPx8hT0wz96gASM5jixZspNECoWjkzmtuwlgXhOc8HvGvqmpUlXGzqkz30hjeC+VCd05200uVBsy9dPv1Xm0pykk5pp6FmXuW+8I+gtqj6u302SnjBYSYA+zxPKRTglWoOmErc0QCqviVgDdijztO24fRBCWCwpxw7lT0SeWPl9WUXbkF07zVNKncyBJyXQAtIePDjFwKvIWyrQi6nNLsSn9zbDn2K5UrXZYa10pEYxgv0cGkCiocaZRDEMxdyh/i+nmeVAMgicQRduESywxGM06Q9e6kbceZl54AdMdZ7Dz8/esMPiecGWYXBKItXbxU2JwXpvmR40BeRM+9BsQssUGYAj7UXaDxM+q7Nh0DA+bsTGct31cl5PsDck4XtCjBunEsgt3Q8ljXLiPC/DdtjMalD28lRg5oecTJO4d6KQwD/Tn4Y1J4fiGUg=
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
