# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-
jobs:
- job: osx
  pool:
    vmImage: macOS-11
  strategy:
    matrix:
      osx_64_python3.10.____cpython:
        CONFIG: osx_64_python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.7.____cpython:
        CONFIG: osx_64_python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____73_pypy:
        CONFIG: osx_64_python3.8.____73_pypy
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpython:
        CONFIG: osx_64_python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____73_pypy:
        CONFIG: osx_64_python3.9.____73_pypy
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpython:
        CONFIG: osx_64_python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_arm64_python3.10.____cpython:
        CONFIG: osx_arm64_python3.10.____cpython
        UPLOAD_PACKAGES: 'True